---
# tasks file for ansible-docker

- name: Install package foo from repo
  pacman:
    name: docker-compose
    state: present

- name: Add the user "{{ansible_user}}" to the group 'docker'
  become: yes
  register: group_add
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes

- name: Install required python-docker packages
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-docker', 'python3-docker' ]