---
# tasks file for ansible-docker

- name: Gather instance facts
  setup:
    
- include_tasks: "docker-{{ ansible_distribution }}.yml"

- name: Add the user {{ ansible_env.USER }}" to the group 'docker'
  become: yes
  register: group_add
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes